ARG NET_IMAGE=8.0.1-bookworm-slim
FROM mcr.microsoft.com/dotnet/aspnet:${NET_IMAGE}
WORKDIR /app
ARG rpc_port=2200
ARG publish_dir
ENV TZ=Asia/Shanghai 
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone 
COPY ${publish_dir} .
EXPOSE ${rpc_port} 
ENTRYPOINT ["dotnet", "SilkyAppHost.dll"]