// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Silky.Account.EntityFrameworkCore;

namespace Silky.Account.Database.Migrations.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20210803133512_v1.0.0")]
    partial class v100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Silky.Account.Domain.Accounts.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.Property<decimal>("LockBalance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "beijing",
                            Balance = 200m,
                            CreateTime = new DateTime(2021, 8, 3, 21, 35, 12, 371, DateTimeKind.Local).AddTicks(8680),
                            Email = "admin@silky.com",
                            LockBalance = 0m,
                            Password = "de4b550727f5b0ff46328be48c0765c3",
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "beijing",
                            Balance = 500m,
                            CreateTime = new DateTime(2021, 8, 3, 21, 35, 12, 371, DateTimeKind.Local).AddTicks(8990),
                            Email = "liuhll@silky.com",
                            LockBalance = 0m,
                            Password = "909e74b36a584cb99e9a83636933a39b",
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "liuhll"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "shenzhen",
                            Balance = 3000m,
                            CreateTime = new DateTime(2021, 8, 3, 21, 35, 12, 371, DateTimeKind.Local).AddTicks(9030),
                            Email = "lisi@silky.com",
                            LockBalance = 0m,
                            Password = "01efe69ed557b5525b5cc4c8f98ac7db",
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "lisi"
                        });
                });

            modelBuilder.Entity("Silky.Account.Domain.Accounts.BalanceRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("OrderBalance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("PayStatus")
                        .HasColumnType("int");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("BalanceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
